#!/bin/bash

echo 'inlining/concatenating...'
mkdir bundle
cp public/bower.json bundle
cp -r public/images bundle
vulcanize --inline-scripts --inline-css --strip-comments public/index.html > bundle/index.build.html

echo 'building/xfering tarball...'
tar -zcf build.tar.gz bundle/*
rm -rf bundle/
scp build.tar.gz luke@lukep.me:~/

echo 'executing server-side build script...'
ssh luke@lukep.me './build'
