export const UPDATE_SELECTED_FILTER_ID = 'date-night/UPDATE_SELECTED_FILTER_ID';
export const ACTIVATE_FILTER_SELECTOR = 'date-night/ACTIVATE_FILTER_SELECTOR';
export const DEACTIVATE_FILTER_SELECTOR = 'date-night/DEACTIVATE_FILTER_SELECTOR';
